=== damooo/vv-samsadhani/SHMT/data/hi/Apte_dict/apte.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT dict (lexhead*)>
<!ELEMENT lexhead (#PCDATA|dentry|prAwipaxikam|cat|gen|etymology|sense|sublexhd|segmenthd|compoundverb|subsegmenthd|jAwi|upAXi|is_a_part|kind_of|grammar|compound|seg|num)*>
<!ELEMENT segmenthd (#PCDATA|dentry|prAwipaxikam|seg|cat|gen|etymology|sense|subsegmenthd|is_a_part|kind_of|jAwi|upAXi|grammar)*>
<!ATTLIST lexhead no CDATA #REQUIRED>
<!ELEMENT dentry (#PCDATA|h|seg)*>
<!ELEMENT prAwipaxikam (#PCDATA|seg)*>
<!ATTLIST prAwipaxikam gen CDATA #IMPLIED>
<!ELEMENT cat (#PCDATA)>
<!ELEMENT gen (#PCDATA)>
<!ELEMENT num (#PCDATA)>
<!ELEMENT grammar (#PCDATA|paxI|gaNa|vform)*>
<!ELEMENT compound (#PCDATA|sense|dentry|prAwipaxikam|grammar|seg|etymology)*>
<!ELEMENT etymology (#PCDATA|citation|vform)*>
<!ELEMENT vform (#PCDATA)>
<!ELEMENT is_a_part (#PCDATA)>
<!ELEMENT kind_of (#PCDATA)> 
<!ELEMENT jAwi (#PCDATA)>
<!ELEMENT upAXi (#PCDATA)>
<!ELEMENT paxI (#PCDATA)>
<!ELEMENT gaNa (#PCDATA)>
<!ELEMENT sense (#PCDATA|ref|citation|vform)*>
<!ATTLIST sense no CDATA #IMPLIED>
<!ATTLIST sense n CDATA #IMPLIED>
<!ELEMENT seg (#PCDATA)>
<!ELEMENT citation (#PCDATA|citation)*>
<!ELEMENT subsegmenthd (#PCDATA|root|seg|cat|gen|etymology|sense|prAwipaxikam|grammar|dentry)*>
<!ELEMENT compoundverb (#PCDATA|root|seg|cat|gen|etymology|sense)*>
<!ELEMENT sublexhd (#PCDATA|root|seg|cat|gen|etymology|sense)*>

=== damooo/vv-samsadhani/SHMT/data/hi/Apte_dict/D.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dict SYSTEM "apte.dtd">
<?xml-stylesheet href="apte.css" type="text/css" ?>
<dict>
<lexhead no="1">
<root>ढक्का</root>
<prAwipaxikam>ढक्का</prAwipaxikam>
<grammar>स्त्री*</grammar>
<etymology><vigraha_vAkya>ढक् इति शब्देन कायति</vigraha_vAkya>[ढक्+कै+क+टाप्]</etymology>
<kind_of>मुरजादिवाद्यम्</kind_of>
<upAXi>वाद्योपकरणम्</upAXi>
<sense no="1">बड़ा ढोल, न ते हुडुक्केन न सोपि ढक्कया न मर्दलैः सापि न तेऽपि ढक्कया<citation>नै* १५/१७</citation></sense>
</lexhead>

<lexhead no="2">
<root>ढामरा</root>
<prAwipaxikam>ढामरा</prAwipaxikam>
<grammar>स्त्री*</grammar>
<sense no="1">हंसनी</sense>
</lexhead>

<lexhead no="3">
<root>ढालम्</root>
<prAwipaxikam>ढाल</prAwipaxikam>
<grammar>नपुं*</grammar>
<sense no="1">म्यान्</sense>
</lexhead>

<lexhead no="4">
<root>ढालिन्</root>
<prAwipaxikam>ढालिन्</prAwipaxikam>
<grammar>पुं*</grammar>
<etymology>[ढाल+इनि]</etymology>
<sense no="1">ढालधारी योद्धा</sense>
</lexhead>

<lexhead no="5">
<root>ढुण्ढिः</root>
<prAwipaxikam>ढुण्ढि</prAwipaxikam>
<grammar>पुं*</grammar>
<etymology>[ढुण्ढ्+इन्]</etymology>
<sense no="1">गणेश का विशेषण</sense>
</lexhead>

<lexhead no="6">
<root>ढौलः</root>
<prAwipaxikam>ढौल</prAwipaxikam>
<grammar>पुं*</grammar>
<sense no="1">बड़ा ढोल, मृदङ्ग, ढपली</sense>
</lexhead>

<lexhead no="7">
<root>ढौक्</root>
<prAwipaxikam>ढौक्</prAwipaxikam>
<grammar><gaNa>भ्वा*</gaNa><paxI>आ*</paxI><vform>ढौकते</vform>,<vform>ढौकित</vform></grammar>
<sense no="1">जाना, पहुँचाना, यान्तं वने रात्रिचरी डुढौके<citation>भट्टि*२/२३</citation>१४/७१, १५/७९</sense>
<sense n="2">निकट लाना, पहुँचानातन्मान्सं चैव गोमायिस्तैः क्षणादाशु ढौकितम्<citation>महा*</citation><citation>भट्टि*१७/१०३</citation></sense>
<sense n="3">उपस्थित करना, प्रस्तुत करना</sense>
</lexhead>

<lexhead no="8">
<root>ढौकनम्</root>
<prAwipaxikam>ढौकन</prAwipaxikam>
<grammar>नपुं*</grammar>
<etymology>[ढौक्+ल्युट्]</etymology>
<sense no="1">भेंट</sense>
<sense no="2">F</sense>
</lexhead>

</dict>

=== damooo/vv-samsadhani/SHMT/data/hi/Apte_dict/t.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dict SYSTEM "apte.dtd">
<?xml-stylesheet href="apte.css" type="text/css" ?>
<dict>
<lexhead no="1">
<root>टङ्क्</root>
<prAwipaxikam>टङ्क्</prAwipaxikam>
<grammar><gaNa>चुरा*</gaNa><paxI>उभ*</paxI><vform>टङ्कयति</vform>,<vform>टङ्कयते</vform>,<vform>टङ्कित</vform></grammar>
<sense no="1">बाँधना, कसना, जकड़ना</sense>
<sense n="2">ढकना</sense>
<segmenthd>
<root>उट्टङ्क्</root>
<prAwipaxikam>उट्टङ्क्</prAwipaxikam>
<seg>उद्-टङ्क्</seg>
<grammar><gaNa>चुरा*</gaNa><paxI>उभ*</paxI></grammar>
<sense no="1">छीलना, खुरचना</sense>
<sense no="2">छिद्र करना, सूराख करना</sense>
</segmenthd>
</lexhead>

<lexhead no="2">
<root>टङ्कः</root>
<prAwipaxikam>टङ्क</prAwipaxikam>
<grammar>पुं*</grammar>
<etymology>[टङ्क+घञ्/टङ्क+अच्]</etymology>
<kind_of>मनोविकारः</kind_of>
<jAwi>मानसिकभावः</jAwi>
<jAwi>क्रिया</jAwi>
<kind_of>आयुधम्</kind_of>
<upAXi>आयुधम्</upAXi>
<sense no="1">कुल्हाड़ी, कुठार, टाँकी, टङ्कैर्मनःशिलगुहेव विदार्यमाणा<citation>मृच्छ*१/२०</citation><citation>रघु*१२/८०</citation>पत्थर काटने या गढ़ने के छेनी</sense>
<sense n="2">तलवार</sense>
<sense n="3">म्यान</sense>
<sense n="4">कुल्हाड़ी की धार के आकार की चोटी, पहाड़ी की ढाल या झुकावF<citation>भट्टि*१/८</citation></sense>
<sense n="5">क्रोध</sense>
<sense n="6">घमण्ड</sense>
<sense n="7">पैर</sense>
</lexhead>

<lexhead no="3">
<root>टङ्का</root>
<prAwipaxikam>टङ्का</prAwipaxikam>
<grammar>स्त्री*</grammar>
<sense no="1">पैर, लात</sense>
</lexhead>

<lexhead no="4">
<root>टङ्कम्</root>
<prAwipaxikam>टङ्क</prAwipaxikam>
<grammar>नपुं*</grammar>
<etymology>[टङ्क+घञ्/टङ्क+अच्]</etymology>
<kind_of>मनोविकारः</kind_of>
<jAwi>मानसिकभावः</jAwi>
<jAwi>क्रिया</jAwi>
<kind_of>आयुधम्</kind_of>
<upAXi>आयुधम्</upAXi>
<sense no="1">कुल्हाड़ी, कुठार, टाँकी, टङ्कैर्मनःशिलगुहेव विदार्यमाणा<citation>मृच्छ*१/२०</citation><citation>रघु*१२/८०</citation>पत्थर काटने या गढ़ने के छेनी</sense>
<sense n="2">तलवार</sense>
<sense n="3">म्यान</sense>
<sense n="4">कुल्हाड़ी की धार के आकार की चोटी, पहाड़ी की ढाल या झुकावF<citation>भट्टि*१/८</citation></sense>
<sense n="5">क्रोध</sense>
<sense n="6">घमण्ड</sense>
<sense n="7">पैर</sense>
</lexhead>

<lexhead no="5">
<root>टङ्ककः</root>
<prAwipaxikam>टङ्कक</prAwipaxikam>
<grammar>पुं*</grammar>
<etymology>[टङ्क+कन्]</etymology>
<sense no="1">चाँदी की सिक्का</sense>
<segmenthd>
<root>टङ्ककपतिः</root>
<prAwipaxikam>टङ्ककपति</prAwipaxikam>
<seg>टङ्ककः-पतिः</seg>
<grammar>पुं*</grammar>
<sense no="2">टकसाल का अध्यक्ष</sense>
</segmenthd>
<segmenthd>
<root>टङ्ककशाला</root>
<prAwipaxikam>टङ्ककशाला</prAwipaxikam>
<seg>टङ्ककः-शाला</seg>
<grammar>स्त्री*</grammar>
<sense no="1">टकसाल</sense>
</segmenthd>
</lexhead>

<lexhead no="6">
<root>टङ्कणम्</root>
<prAwipaxikam>टङ्कण</prAwipaxikam>
<grammar>नपुं*</grammar>
<etymology>[टङ्क्+ल्युट्]</etymology>
<sense no="1">सोहागा</sense>
</lexhead>

<lexhead no="7">
<root>टङ्कनम्</root>
<prAwipaxikam>टङ्कन</prAwipaxikam>
<grammar>नपुं*</grammar>
<etymology>[टङ्क्+ल्युट्]</etymology>
<sense no="1">सोहागा</sense>
</lexhead>

<lexhead no="8">
<root>टङ्कणः</root>
<prAwipaxikam>टङ्कण</prAwipaxikam>
<grammar>पुं*</grammar>
<sense no="1">घोड़े की एक जाति</sense>
<sense n="2">एक देश विशेष के निवासी</sense>
</lexhead>

<lexhead no="9">
<root>टङ्कनः</root>
<prAwipaxikam>टङ्कन</prAwipaxikam>
<grammar>पुं*</grammar>
<sense no="1">घोड़े की एक जाति</sense>
<sense n="2">एक देश विशेष के निवासी</sense>
<segmenthd>
<root>टङ्कणक्षारः</root>
<prAwipaxikam>टङ्कणक्षार</prAwipaxikam>
<seg>टङ्कणम्-क्षारः</seg>
<grammar>पुं*</grammar>
<sense no="1">सोहागा</sense>
</segmenthd>
</lexhead>

<lexhead no="10">
<root>टङ्कारः</root>
<prAwipaxikam>टङ्कार</prAwipaxikam>
<grammar>पुं*</grammar>
<etymology>[टम्-कृ+अण्]</etymology>
<sense no="1">धनुष की डोर खींचने से होने वाली ध्वनि</sense>
<sense n="2">गुर्राना, चिल्लाना, चीत्कार, चीख</sense>
</lexhead>

<lexhead no="11">
<root>टङ्कारिन्</root>
<prAwipaxikam>टङ्कारिन्</prAwipaxikam>
<grammar>वि*</grammar>
<prAwipaxikam gen="स्त्री">टङ्कारिन्</prAwipaxikam>
<etymology>[टङकार+इनि]</etymology>
<sense no="1">टंकार करने वाला, फुत्कार या सीत्कार करने वाला; झङ्कार करने वाला, टङ्कारिचापमनु लङ्काशरक्षतजपङ्कावरूषितशरम्<citation>अस्व*१</citation></sense>
</lexhead>

<lexhead no="12">
<root>टङ्किका</root>
<prAwipaxikam>टङ्किका</prAwipaxikam>
<grammar>स्त्री*</grammar>
<etymology>[टङ्क्+कन्+टाप् ,(इत्वम्)]</etymology>
<sense no="1">टाँकी, कुल्हाड़ी<citation>विक्रमांक*१/१५</citation></sense>
</lexhead>

<lexhead no="13">
<root>टङ्गः</root>
<prAwipaxikam>टङ्ग</prAwipaxikam>
<grammar>पुं*</grammar>
<etymology>[टङ्कः पृषो*]</etymology>
<sense no="1">कुदाल, खुर्पा, कुल्हाड़ी</sense>
</lexhead>

<lexhead no="14">
<root>टङ्गम्</root>
<prAwipaxikam>टङ्ग</prAwipaxikam>
<grammar>नपुं*</grammar>
<etymology>[टङ्कः पृषो*]</etymology>
<sense no="1">कुदाल, खुर्पा, कुल्हाड़ी</sense>
</lexhead>

<lexhead no="15">
<root>टङ्गणः</root>
<prAwipaxikam>टङ्गण</prAwipaxikam>
<grammar>पुं*</grammar>
<etymology>[टङ्कः पृषो*]</etymology>
<sense no="1">सोहागा</sense>
</lexhead>

<lexhead no="16">
<root>टङ्गणम्</root>
<prAwipaxikam>टङ्गण</prAwipaxikam>
<grammar>नपुं*</grammar>
<etymology>[टङ्कः पृषो*]</etymology>
<sense no="1">सोहागा</sense>
</lexhead>

<lexhead no="17">
<root>टङ्गा</root>
<prAwipaxikam>टङ्गा</prAwipaxikam>
<grammar>स्त्री*</grammar>
<etymology>[टङ्ग+टाप्]</etymology>
<sense no="1">टाँग, लात, पैर</sense>
</lexhead>

<lexhead no="18">
<root>टहरी</root>
<prAwipaxikam>टहरी</prAwipaxikam>
<grammar>स्त्री*</grammar>
?<etymology>[टहेति शब्दं राति रा+क+ङीष्]</etymology>
<sense no="1">एक प्रकार का वाद्ययन्त्र</sense>
<sense n="2">परिहास, ठठ्ठा</sense>
</lexhead>

<lexhead no="19">
<root>टाङ्कारः</root>
<prAwipaxikam>टाङ्कार</prAwipaxikam>
<grammar>पुं*</grammar>
<etymology>[टङ्कार+अण्]</etymology>
<sense no="1">झंकार, टङ्कार</sense>
</lexhead>

<lexhead no="20">
<root>टिक्</root>
<prAwipaxikam>टिक्</prAwipaxikam>
<grammar><gaNa>भ्वा*</gaNa><paxI>आ*</paxI><vform>टेकते</vform></grammar>
<sense no="1">जाना, चलना-फिरना</sense>
</lexhead>

<lexhead no="21">
<root>टिटिभः</root>
<prAwipaxikam>टिटिभ</prAwipaxikam>
<grammar>पुं*</grammar>
<etymology><vigraha_vAkya>टिटि इत्यव्यक्तशब्दं भणति</vigraha_vAkya>[ टिटि-भण्+ड]</etymology>
<sense no="1">टिटिहिरी पक्षी, उत्क्षिप्य टिट्टिभः पादावास्ते भङ्गभयाद्दिवः<citation>पंच*१/३१४</citation><citation>मनु*५/११</citation><citation>याज्ञ*१/७२</citation>स्त्री* टिटि ट्टि भी ’टिट्टिभक’भी</sense>
</lexhead>

<lexhead no="22">
<root>टिट्टिभः</root>
<prAwipaxikam>टिट्टिभ</prAwipaxikam>
<grammar>पुं*</grammar>
<etymology><vigraha_vAkya>टिट्टि इत्यव्यक्तशब्दं भणति</vigraha_vAkya>[ टिट्टि+भण्+ड]</etymology>
<sense no="1">टिटिहिरी पक्षी, उत्क्षिप्य टिट्टिभः पादावास्ते भङ्गभयाद्दिवः<citation>पंच*१/३१४</citation><citation>मनु*५/११</citation><citation>याज्ञ*१/७२</citation>स्त्री* टिटि ट्टि भी ’टिट्टिभक’भी</sense>
</lexhead>

<lexhead no="23">
<root>टिप्पणी</root>
<prAwipaxikam>टिप्पणी</prAwipaxikam>
<grammar>स्त्री*</grammar>
?<etymology>[टिप्+क्विप्, टिपा पन्यते स्तूयते टिप्+पन्+अच्+ङीष्, पृषो* पात्वं वा]</etymology>
<sense no="1">भाष्य, टीका, कभी-कभी ’भाष्य’ पर लिखी गई ’व्याख्या’ के लिए भी- उदा* महाभाष्य पर कैयट की व्याख्या या टीका या कैयट के भाष्य पर नागोजी भट्ट की टीका या भाष्य</sense>
</lexhead>

<lexhead no="24">
<root>टिप्पनी</root>
<prAwipaxikam>टिप्पनी</prAwipaxikam>
<grammar>स्त्री*</grammar>
?<etymology>[टिप्+क्विप्, टिपा पन्यते स्तूयते टिप्+पन्+अच्+ङीष्, पृषो* पात्वं वा]</etymology>
<sense no="1">भाष्य, टीका, कभी-कभी ’भाष्य’ पर लिखी गई ’व्याख्या’ के लिए भी- उदा* महाभाष्य पर कैयट की व्याख्या या टीका या कैयट के भाष्य पर नागोजी भट्ट की टीका या भाष्य</sense>
</lexhead>

<lexhead no="25">
<root>टीक्</root>
<prAwipaxikam>टीक्</prAwipaxikam>
<grammar><gaNa>भ्वा*</gaNa><paxI>आ*</paxI><vform>टीकते</vform></grammar>
<sense no="1">चलना- फिरना, जाना, सहारा, देना, कश्मर्याः कृतमालमुद्गतदलं कोयष्टिकष्टीकते<citation>मा*९/७</citation></sense>
<segmenthd>
<root>आटीक्</root>
<prAwipaxikam>आटीक्</prAwipaxikam>
<seg>आ-टीक्</seg>
<grammar><gaNa>भ्वा*</gaNa><paxI>आ*</paxI></grammar>
<sense no="1">जाना, चलना-फिरना, इधर-उधर घूमनाआटीकसेऽङ्ग करिघोटीपदातिजुषि वाटीउवि क्षितिभुजाम्<citation>अश्व*५</citation></sense>
</segmenthd>
</lexhead>

<lexhead no="26">
<root>टीका</root>
<prAwipaxikam>टीका</prAwipaxikam>
<grammar>स्त्री*</grammar>
<etymology><vigraha_vAkya>टीक्यते गम्यते, ग्रन्थार्थोऽनया</vigraha_vAkya>[टीक्+क+टाप्]</etymology>
<sense no="1">व्याख्या, भाष्य, काव्यप्रकाशस्य कृता गृहे गृहे टीका तथाप्येष तथैव दुर्गमः</sense>
</lexhead>

<lexhead no="27">
<root>टुण्टुक</root>
<prAwipaxikam>टुण्टुक</prAwipaxikam>
<grammar>वि*</grammar>
<prAwipaxikam gen="स्त्री">टुण्टुक</prAwipaxikam>
<etymology><vigraha_vAkya>टुण्टु इति अव्यक्तशब्दं कायति</vigraha_vAkya>[टुटु-कै+क]</etymology>
<kind_of>वृक्षः</kind_of>
<jAwi>वृक्षः</jAwi>
<sense no="1">छोटा, थोड़ा</sense>
<sense n="2">दुष्ट, क्रूर, नृशंस</sense>
<sense no="3"></sense>
</lexhead>

</dict>

=== damooo/vv-samsadhani/SHMT/data/hi/Apte_dict/T.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dict SYSTEM "apte.dtd">
<?xml-stylesheet href="apte.css" type="text/css" ?>
<dict>
<lexhead no="1">
<root>ठः</root>
<prAwipaxikam>ठ</prAwipaxikam>
<grammar>पुं*</grammar>
<sense no="1">अनुकरणात्मक ध्वनिः, रामाभिषेके मदविह्वलायाः कक्षाच्च्युतो हेमघटस्तरुण्याः, सोपानमार्गे प्रकरोति शब्दं ठठं ठठंठं ठठठं ठठंठः<citation>सुभा*</citation>धातु के बने बर्तन के सीढ़ियों में से गिरते हुए ध्वनि जैसी</sense>
</lexhead>

<lexhead no="2">
<root>ठक्कुरः</root>
<prAwipaxikam>ठक्कुर</prAwipaxikam>
<grammar>पुं*</grammar>
<sense no="1">मूर्ति, देवमूर्ति</sense>
<sense n="2">पूज्य व्यक्ति के नाम के साथ लगने वाली सम्मानसूचक उपाधि Fउदा* गोविन्द ठक्कुर काव्यप्रदीप के रचयिता</sense>
</lexhead>

<lexhead no="3">
<root>ठालिनी</root>
<prAwipaxikam>ठालिनी</prAwipaxikam>
<grammar>स्त्री*</grammar>
<sense no="0">तगड़ी, करधनी</sense>
</lexhead>

</dict>

=== damooo/vv-samsadhani/SHMT/data/hi/Apte_dict/W.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dict SYSTEM "apte.dtd">
<?xml-stylesheet href="apte.css" type="text/css" ?>
<dict>
<lexhead no="1">
<root>थः</root>
<prAwipaxikam>थ</prAwipaxikam>
<grammar>पुं*</grammar>
<etymology>[थुड्+ड]</etymology>
<sense no="1">पहाड़</sense>
</lexhead>

<lexhead no="2">
<root>थम्</root>
<prAwipaxikam>थ</prAwipaxikam>
<grammar>नपुं*</grammar>
<sense no="1">रक्षा, प्ररक्षा</sense>
<sense n="2">त्रास, भय</sense>
<sense n="3">मांगलिकता</sense>
</lexhead>

<lexhead no="3">
<root>थुड्</root>
<prAwipaxikam>थुड्</prAwipaxikam>
<grammar><gaNa>तुदा*</gaNa><paxI>पर*</paxI><vform>थुडति</vform></grammar>
<sense no="1">ढकना, पर्दा डालना</sense>
<sense n="2">छिपाना, गुप्त रखना</sense>
</lexhead>

<lexhead no="4">
<root>थुडनम्</root>
<prAwipaxikam>थुडन</prAwipaxikam>
<grammar>नपुं*</grammar>
<etymology>[थुड्+ल्युट्]</etymology>
<sense no="1">ढकना, लपेटना</sense>
</lexhead>

<lexhead no="5">
<root>थुत्कारः</root>
<prAwipaxikam>थुत्कार</prAwipaxikam>
<grammar>पुं*</grammar>
<etymology>[थुत्-कृ+अण्]</etymology>
<sense no="1">‘थुत्’ ध्वनि जो थूकने की क्रिया करते समय होती है</sense>
</lexhead>

<lexhead no="6">
<root>थुर्व्</root>
<prAwipaxikam>थुर्व्</prAwipaxikam>
<grammar><gaNa>भ्वा*</gaNa><paxI>पर*</paxI><vform>थूर्वति</vform></grammar>
<sense no="1">चोट पहुँचाना, क्षति पहुँचाना</sense>
</lexhead>

<lexhead no="7">
<root>थूत्कारः</root>
<prAwipaxikam>थूत्कार</prAwipaxikam>
<grammar>पुं*</grammar>
<etymology>[थुत्-कृ+अण्]</etymology>
<sense no="1">‘थुत्’ की ध्वनि जो थूकने की क्रिया करते समय होती है</sense>
</lexhead>

<lexhead no="8">
<root>थूत्कृतम्</root>
<prAwipaxikam>थूत्कृत</prAwipaxikam>
<grammar>नपुं*</grammar>
<etymology>[थुत्-कृ+अण्/थुत्-कृ+क्त]</etymology>
<sense no="1">‘थुत्’ की ध्वनि जो थूकने की क्रिया करते समय होती है</sense>
</lexhead>

<lexhead no="9">
<root>थैथै</root>
<prAwipaxikam>थैथै</prAwipaxikam>
<grammar>अव्य*</grammar>
<sense no="1">किसी संगीत-वाद्य-यंत्र की अनुकरणात्मक ध्वनि</sense>
</lexhead>

</dict>
